### ISSUE TITLE
Not support Add global Interceptors for ironrhino framework 

### ISSUE THREAD

**Issue by wujianfeirun** [ironrhino/ironrhino#37]
When i add a struts.xml in the project source directory,add LogInterceptor for all Action, the config as follow:

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE struts PUBLIC
	"-//Apache Software Foundation//DTD Struts Configuration 2.0//EN"
	"http://struts.apache.org/dtds/struts-2.0.dtd">
	
<struts>
	<package name="demo-struts" extends="ironrhino-default">
		<interceptors>
			<interceptor name="LogInterceptor" class="com.mypractice.interceptor.LogInterceptor"/>
			<interceptor-stack name="logStack">
				<interceptor-ref name="LogInterceptor"/>
			</interceptor-stack>
		</interceptors>
		<default-interceptor-ref name="logStack"/>
	</package>
</struts>

But it won't work ， pls give some advise， Thanks so much

**Comment by quaff** [comment]
推荐使用Spring的AOP来实现拦截功能
