### ISSUE TITLE
Spring Boot + ironrhino ？

### ISSUE THREAD

**Issue by zhao-mingjian** [ironrhino/ironrhino#39]
是这样的，由于我们同事用了您们的框架 ironrhino，而且是使用 Ant 编译的，目前交接给我了，目标是想升级到 Maven，同时将项目结构切换为 Spring Boot + ironrhino，
目前这方面网络资料比较少，请教一下有什么好的方法或者 Demo 吗？

**Comment by quaff** [comment]
切换成maven或者gradle应该有点难度，我目前也在做一个用Gradle构建的Spring Boot项目，尽量把ironrhino的功能搬过去，但是杀手锏功能一键CRUD估计不会，只作为纯后端Rest API的服务端，界面交给专门的前端处理。

**Comment by zhao-mingjian** [comment]
是的，我们也是想做成前后端分离的，后端只纯粹提供接口，感谢回复。期待你的船新版本。
